// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: foo.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GreetReq) Validate() error {
	return nil
}
func (this *GreetResp) Validate() error {
	return nil
}
